# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180304_1033'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
