# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-04 17:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_auto_20180404_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='event_date_time',
        ),
        migrations.AddField(
            model_name='event',
            name='event_date',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='event_time',
            field=models.TimeField(null=True),
        ),
    ]
