# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-05 09:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_auto_20180404_2251'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date', 'event_time']},
        ),
    ]
