# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 08:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0004_auto_20180405_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='event_details',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
