# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-06 18:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0006_auto_20180407_0014'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['event_date_time']},
        ),
        migrations.RenameField(
            model_name='event',
            old_name='event_time',
            new_name='event_date_time',
        ),
        migrations.RemoveField(
            model_name='event',
            name='event_date',
        ),
    ]
