# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-22 15:25
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_auto_20180304_1033'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('assignment', '0003_auto_20180322_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Slide',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_name', models.CharField(max_length=50)),
                ('slide_file', models.FileField(null=True, upload_to='slide', verbose_name='Slide')),
                ('in_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='profiles.Course')),
                ('uploaded_by', models.ForeignKey(default=b'authtools.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-pk'],
            },
        ),
        migrations.AlterField(
            model_name='assignment',
            name='uploaded_by',
            field=models.ForeignKey(default=b'authtools.User', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
