# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-28 05:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0004_auto_20180322_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
