# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0005_assignment_share'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='assignment_file',
            field=models.FileField(null=True, upload_to='assignment/%Y/%m/%d/', verbose_name='Assignment'),
        ),
    ]
