# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-03-30 20:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_auto_20180331_0152'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='for_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
