# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0007_assignment_for_semester'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='in_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='in_course', to='profiles.Course'),
        ),
    ]
