# -*- coding: utf-8 -*-
# Generated by Django 1.11.10 on 2018-04-01 13:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0008_auto_20180401_1455'),
    ]

    operations = [
        migrations.AddField(
            model_name='slide',
            name='for_semester',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='slide',
            name='share',
            field=models.BooleanField(default=False),
        ),
    ]
